language: go

addons:
  postgresql: "9.6"

go:
  - 1.16.x
  - tip

matrix:
  allow_failures:
    - go: tip

go_import_path: github.com/go-pg/migrations

before_install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.21.0
